version: "3.7"
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
